# Use root/example as user/password credentials
version: '3.1'

services:
  censusdot_mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOPWD}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOUSER}
    volumes:
      - "${DATA_DIR}/mongodb:/data/db"
    ports:
      - "27017:27017"